name: Continuous Integration
on: [push, pull_request]
env:
  BUILD_TYPE: Release
jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Env
      run: cmake -E make_directory ${{runner.workspace}}/target
    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/target
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/target
      run: cmake --build . --config $BUILD_TYPE
    - name: Test
      shell: bash
      working-directory: ${{runner.workspace}}/target
      run: ctest -C $BUILD_TYPE --output-on-failure

