name: Continuous Integration
on: [push, pull_request]
jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Env
      run: cmake -E make_directory ${{runner.workspace}}/target
    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/target
      run: cmake $GITHUB_WORKSPACE
    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/target
      run: cmake --build .
    - name: Test
      shell: bash
      working-directory: ${{runner.workspace}}/target
      run: ctest --output-on-failure

